sudo: required
dist: trusty
language: php

php:
- 7.1.
   
branches:
only:
- master #-> Staging Server
- develop #-> DevServer

#sebelum melakukan atau eksekusi script
#install kebutuhan OS. ext: mod-php dll.
before_install:
- curl -LO http://storage.googleapis.com/kubernetes-release/$(curl -s http://storage.googleapis.com/kubernetes-release/release/stable.txt) /bin/linux/amd64/kubect1
- chmod +x ./kubect1
- sudo mv ./kubect1 /usr/local/bin/kubect1
- kubect1

#Pre Execution
before_script:

#main execution
script: